#ifndef __HI_PMU_H__
#define __HI_PMU_H__ 
#ifndef BSP_CONFIG_BOARD_TELEMATIC
#define CONFIG_PMU_APT 
#endif
#define PMIC_VOLT_MIN 0
#define PMIC_VOLT_MAX 35
#define PMIC_VOLT_NUM (PMIC_VOLT_MAX - PMIC_VOLT_MIN +1)
#define PMIC_HI6559 
#ifdef BSP_CONFIG_SFT
#define PMIC_BASE_ADDR 0x81FD8000
#else
#define PMIC_BASE_ADDR 0x9001a000
#endif
#define PMIC_IOSHARE_FUNC 
#define PMU_INT_POWER_KEY_1SS_PRESS 5
#define PMU_INT_POWER_KEY_20MS_RELEASE 6
#define PMU_INT_POWER_KEY_20MS_PRESS 7
#define PMU_INT_USB_OUT 2
#define PMU_INT_USB_IN 1
#define PMU_INT_SIM0_RAISE 24
#define PMU_INT_SIM0_FALL 25
#define PMU_INT_SIM1_RAISE 28
#define PMU_INT_SIM1_FALL 29
#define DELAY_VALUE 0x4
#define DELAY_ADDR 0x81FD6074
#define PMIC_POWERKEY_STATE_REG 0x006
#define PMIC_POWERKEY_STATE_MASK 0x80
#define PMIC_USB_STATE_REG 0x007
#define PMIC_USB_STATE_MASK 0x80
#define PMIC_HRESET_PWRDOWN_CTRL 0x10B
#define PMIC_HRESET_STATE_REG 0x22b
#define PMIC_HRESET_STATE_REG_RECINDEX 0x1
#define PMIC_HRESET_STATE_REG_IRQINDEX 0x0
#define PMIC_HRESET_STATE_MASK 0x1
#define PMIC_VERSION_REG0 0x00
#define PMIC_VERSION_REG1 0x01
#define PMIC_VERSION_REG2 0x02
#define PMIC_VERSION_REG3 0x03
#define PMIC_VERSION_REG4 0x04
#define PMIC_VERSION_REG5 0x05
#define PMIC_LCDIO_ENABLE_REG 0x018
#define PMIC_LCDIO_ENABLE_MASK 0x01
#define PMIC_LCDIO_ENABLE_VALUE 0x01
#define PMIC_LCDIO_DISABLE_REG 0x018
#define PMIC_LCDIO_DISABLE_MASK 0x01
#define PMIC_LCDIO_DISABLE_VALUE 0
#define PMIC_LCDANALOG_ENABLE_REG 0x01f
#define PMIC_LCDANALOG_ENABLE_MASK 0x01
#define PMIC_LCDANALOG_ENABLE_VALUE 0x01
#define PMIC_LCDANALOG_DISABLE_REG 0x01f
#define PMIC_LCDANALOG_DISABLE_MASK 0x01
#define PMIC_LCDANALOG_DISABLE_VALUE 0
#define PMIC_LCDANALOG_VOLT_REG 0x04a
#define PMIC_LCDANALOG_VOLT_MASK 0x07
#define PMIC_LCDANALOG_VOLT_VALUE 0x2
#define PMIC_EFUSE_ENABLE_REG 0x027
#define PMIC_EFUSE_ENABLE_MASK 0x01
#define PMIC_EFUSE_ENABLE_VALUE 0x01
#define PMIC_EFUSE_DISABLE_REG 0x027
#define PMIC_EFUSE_DISABLE_MASK 0x01
#define PMIC_EFUSE_DISABLE_VALUE 0
#define PMIC_IRQ_NUM 4
#define PMIC_GPIO_IRQ_NUM 1
#define PMIC_OCP_IRQ_NUM 4
#define PMIC_RECORD_NUM 7
#define PMIC_OCP_NCP_BASE 0x224
#define PMIC_IRQ_NCP_BASE 0x220
#define PMIC_GPIO_IRQ_NCP_BASE 0x228
#define PMIC_RECORD_NCP_BASE 0x22a
#define PMIC_OVP_MASK 0x01
#define PMIC_OTP_MASK 0x10
#define PMIC_OCP_MASK 0x01
#define OCP_RECORD_START 0x2
#define OCP_RECORD_NUM 0x3
#define PMIC_LCD_IO_ID 7
#define PMIC_LCDANALOG_ID 21
#define PMIC_EFUSE_ID 9
#define PMIC_HI6559_BUCK1 1
#define PMIC_HI6559_LDO0 4
#define COUL_V_OUT0_PRE0_OFFSET 0x27b
#define COUL_V_OUT1_PRE0_OFFSET 0x27c
#define COUL_CURRENT0_PRE0_OFFSET 0x28f
#define COUL_CURRENT1_PRE0_OFFSET 0x290
#define COUL_CL_IN0_OFFSET 0x259
#define COUL_CL_IN1_OFFSET 0x25a
#define COUL_CL_IN2_OFFSET 0x25b
#define COUL_CL_IN3_OFFSET 0x25c
#define COUL_CL_OUT0_OFFSET 0x255
#define COUL_CL_OUT1_OFFSET 0x256
#define COUL_CL_OUT2_OFFSET 0x257
#define COUL_CL_OUT3_OFFSET 0x258
#define COUL_OCV_DATA1_OFFSET 0x26f
#define COUL_OCV_DATA2_OFFSET 0x270
#define COUL_OFFSET_VOLTAGE0_OFFSET 0x26d
#define COUL_OFFSET_VOLTAGE1_OFFSET 0x26e
#define COUL_LOAD_TIMER0_OFFSET 0x261
#define COUL_LOAD_TIMER1_OFFSET 0x262
#define COUL_LOAD_TIMER2_OFFSET 0x263
#define COUL_LOAD_TIMER3_OFFSET 0x264
#define COUL_CHG_TIMER0_OFFSET 0x25d
#define COUL_CHG_TIMER1_OFFSET 0x25e
#define COUL_CHG_TIMER2_OFFSET 0x25f
#define COUL_CHG_TIMER3_OFFSET 0x260
#define COUL_V_INT0_OFFSET 0x269
#define COUL_V_INT1_OFFSET 0x26a
#define COUL_CLJ_CTRL_REG_OFFSET 0x253
#define COUL_CLJ_CTRL_REG2_OFFSET 0x2bb
#define COUL_ECO_REFLASH_TIME_OFFSET 0x254
#define COUL_PMU_SOFT_RST 0x2ae
#define COUL_STATE_TEST_OFFSET 0x2b1
#define COUL_CTRL_ONOFF_MASK (1)
#define COUL_CTRL_CALI_MASK (1<<5)
#define COUL_CTRL_REFLASH_MASK (1<<3)
#define COUL_CTRL_ECO_MASK (1<<2)
#define COUL_CTRL_FILETR_MASK (7<<4)
#define COUL_STATE_MASK 0x7
#endif
