/*************************************************************************
CAUTION : This file is Auto Generated by VBA based on 《V750 MBB PRODUCT_auto_adaptor.xlsm》.
          So, don't modify this file manually!
****************************************************************************/
#ifndef __MBB_PRODUCT_ADAPT_H__
#define __MBB_PRODUCT_ADAPT_H__


#ifdef __cplusplus
extern "C"
{
#endif


/****************************************************************************/
/*************************** MBB 自适配文件开始 *****************************/
/****************************************************************************/
#define    GPIO_NULL                           (-1)               /* 无此GPIO时取-1 */
#define    MENU_KEY_GPIO                       (GPIO_NULL)        /* MENU/WPS键 */
#define    RESET_KEY_GPIO                      (GPIO_0_4)         /* RESET键 */
#define    WIFI_KEY_GPIO                       (GPIO_NULL)        /* WIFI/WLAN键 */
#define    WIFI_ACTIVE_GPIO                    (GPIO_NULL)        /* wifi enable */
#define    WIFI_WAKEUP_BB_GPIO                 (GPIO_NULL)        /* wifi wakeup bb */
#define    LCD_BACKLIGHT_GPIO                  (GPIO_NULL)        /* lcd backlight */
#define    LCD_ID00_GPIO                       (GPIO_NULL)        /* lcd id0 */
#define    LCD_ID01_GPIO                       (GPIO_NULL)        /* lcd id1 */
#define    OLED_ID0_GPIO                       (GPIO_SLEEP_0_0)   /* oled id0 */
#define    OLED_ID1_GPIO                       (GPIO_SLEEP_0_5)   /* oled id1 */
#define    OLED_CD_GPIO                        (GPIO_6_3)         /* oled cd */
#define    OTG_ID_DET_GPIO                     (GPIO_NULL)        /* otg detect */
#define    OTG_ID_SET_GPIO                     (GPIO_NULL)        /* otg set */
#define    DMDP_CONNECT_GPIO                   (GPIO_NULL)        /* dmdp connect */
#define    GPIO_OTG_CPE_MODE                   (GPIO_NULL)        /* GPIO 默认模式（HOST） */
#define    SD_DETECT_GPIO                      (GPIO_NULL)        /* sd detect */
#define    GPS_GPIO                            (GPIO_NULL)        /* GPS芯片使能GPIO */
#define    ETH_PWR_ON_GPIO                     (GPIO_NULL)        /* 底板DCDC使能信号，高电平上电 */
#define    VBUS_POWER_CTRL                     (GPIO_NULL)        /* 单板vbus供电开关 */
#define    VBUS_OVERFLOW_IRQ                   (GPIO_NULL)        /* 单板vbus过流中断用gpio */
#define    LAN_PHY_RESET                       (GPIO_2_6)         /* PHY芯片reset */
#define    LAN_PHY_ADDR                        (GPIO_NULL)        /* BCM89811芯片PHYADDR */
#define    LAN_PHY_MODE1                       (GPIO_NULL)        /* BCM89811芯片模式,与LAN_PHY_MODE2共同使用 */
#define    LAN_PHY_MODE2                       (GPIO_NULL)        /* BCM89811芯片模式,与LAN_PHY_MODE1共同使用 */
#define    WAKEUP_IN                           (GPIO_NULL)        /* WAKEUP_IN */
#define    WAKEUP_OUT                          (GPIO_NULL)        /* WAKEUP_OUT */
#define    SLEEP_STATUS                        (GPIO_NULL)        /* SLEEP_STATUS */
#define    GPIO_VBUS_USBID                     (GPIO_NULL)        /* 722平台ADC复用，通过GPIO控制是VBUS还是USBID */
#define    WIFI_5G_POWER_EN                    (GPIO_NULL)        /* 5GWIFI PA供电的DCDC使能管脚,高电平使能 */
#define    WIFI_ENABLE_PIN                     (GPIO_NULL)        /* WIFI使能管脚 */
#define    BOOT_MODE_SEL_GPIO                  (GPIO_NULL)        /* 通过改GPIO控制是否进入recovery模式 */
#define    IPL_SEL_GPIO                        (GPIO_NULL)        /* 哈曼双倍份镜像选择管脚 */
#define    IPL_KICK_WDT_GPIO                   (GPIO_NULL)        /* kick wdt gpio管脚 */
#define    GPIO_PHY_LOWPOWEREN                 (GPIO_4_6)         /* phy lowpower enable */
#define    WIFI_SAW_SEL0                       (GPIO_SLEEP_1_5)   /* 通路选择GPIO */
#define    WIFI_SAW_SEL1                       (GPIO_SLEEP_1_6)   /* 通路选择GPIO */
#define    NFC_EN                              (GPIO_SLEEP_1_4)   /* NFC使能GPIO */
#define    NFC_INT_GPIO                        (GPIO_0_1)         /* NFC中断GPIO */
#define    LCD_RESET_N                         (GPIO_SLEEP_0_1)   /* LCD reset */

/******************************************************************************/
/***************************** MBB 自适配文件结束 *****************************/
/******************************************************************************/


#ifdef __cplusplus
}
#endif
#endif /*__MBB_PRODUCT_ADAPT_H__ */
