# MD5: 1ce7599202e3cf61f2863c8479af1417
set(CFG_TENSILICA_BUILDS_HIFI $(ROOT_XTENSA_PATH_W)/XtDevTools/install/builds/RE-2014.5-linux) 

set(CFG_TENSILICA_TOOLS_HIFI $(ROOT_XTENSA_PATH_W)/XtDevTools/install/tools/RE-2014.5-linux) 

set(CFG_FEATURE_HIFI FEATURE_OFF) 

set(CFG_FEATURE_HIFI_USE_ICC FEATURE_OFF) 

set(CFG_HIFI_INCLUDE NO) 

set(CFG_HIFI_LINK_DIR_NAME hifi_ld_V7R2_SFT) 

set(CFG_XTENSA_CORE_HIFI v7r2_hifi) 

set(CFG_FEATURE_MBB_MODULE_AUDIO FEATURE_OFF) 

set(CFG_FEATURE_VOICE_UP FEATURE_OFF) 

set(CFG_FEATURE_DTMF FEATURE_ON) 

set(CFG_FEATURE_VOICE_INBAND_DTMF_ELIMINATE FEATURE_OFF) 

