/*
 * Copyright (C) Huawei Technologies Co., Ltd. 2013-2015. All rights reserved.
 *
 * mobile@huawei.com
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 */
/*************************************************************************
CAUTION : This file is Auto Generated by VBA based on 《MBB_AT_whitelist_auto_generator.xlsm》.
          So, don't modify this file manually!
****************************************************************************/


/******************************* 引用头文件 *******************************/
#include "MbbAtCmdFilter.h"





/****************************************************************************/
/*************************** MBB AT 一级白名单列表开始 **********************/
/****************************************************************************/
const VOS_CHAR *gszFilterCmdTable[] = 
{
    "E",    /* 设置AT命令回显状态ATE */
    "I",    /* ATI命令查询MS的相关ID信息ATI */
    "^CURC",    /* 主动上报AT命令控制AT^CURC */
    "^AUTHVER",    /* 获取数据锁版本AT^AUTHVER */
    "^DATALOCK",    /* 设置数据锁命令AT^DATALOCK */
    "^DLOADVER",    /* 查询下载协议版本命令AT^DLOADVER */
    "^DLOADINFO",    /* 获取单板版信息命令AT^DLOADINFO */
    "^NVBACKUP",    /* NV备份命令AT^NVBACKUP */
    "^NVRESTORE",    /* NV恢复命令AT^NVRESTORE */
    "^AUTHORITYVER",    /* 查询升级鉴权方式AT^AUTHORITYVER */
    "^AUTHORITYID",    /* 查询升级鉴权标识AT^AUTHORITYID */
    "^GODLOAD",    /* 切换到下载模式命令AT^GODLOAD */
    "^RESET",    /* 单板重启命令AT^RESET */
    "^NVRSTSTTS",    /* NV自动恢复状态查询命令AT^NVRSTSTTS */
    "^SUPINFO",    /* 向单板侧发送本地PC时间, 升级软件版本号和工具类型AT^SUPINFO */
    "^SN",    /* 产品整机条码号命令AT^SN */
    "^BSN",    /* 单板条码号命令AT^BSN */
};


const VOS_CHAR * MbbAtCmdFilterGetTable(VOS_VOID)
{
    return gszFilterCmdTable;
}


VOS_UINT32 MbbAtCmdFilterGetTableCount(VOS_VOID)
{
    return (sizeof(gszFilterCmdTable) / sizeof(gszFilterCmdTable[0]));
}


/******************************************************************************/
/***************************** MBB AT 一级白名单列表结束 **********************/
/******************************************************************************/


