
/*
 * Copyright (C) Huawei Technologies Co., Ltd. 2013-2015. All rights reserved.
 *
 * mobile@huawei.com
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 */



#include <linux/kernel.h>
#include "bsp_sram.h"
#include "bsp_shared_ddr.h"
#include "dload_nark_api.h"
#include "dload_product.h"
#include <bsp_version.h>

#ifdef  __cplusplus
    extern "C"{
#endif

/******************************************************************************
  1 模块私有 (宏、枚举、结构体、自定义数据类型) 定义区:
******************************************************************************/
#define DLOAD_PRINT(level, fmt, ...) (printk(level"[*DLOAD_PRODUCT*] %s:%d: "fmt"\n", __func__, __LINE__, ##__VA_ARGS__))


#define PRODUCT_OFFSET              (16)
#define SHOW_NOT_DELAY             (0)       /*延时0s*/

static uint8 g_product_id = 0;
static uint8 g_big_ver = 0;
static boolean dload_burn = FALSE;

/* 路径标识码定义 */
typedef enum
{
    LCD_DEV_NAME,       /* LCD设备名称 */
    LCD_PIC_SUCCESS,    /* 升级成功图片名称 */
    LCD_PIC_FAILED,     /* 升级失败图片名称 */
    LCD_PIC_AUTOUG,     /* 在线升级图片名称 */
    LCD_PIC_LOWPOWER,   /* 低电图片名称 */
    LCD_PIC_INSTALL0,   /* 安装过程图片0 */
    LCD_PIC_INSTALL1,   /* 安装过程图片1 */
    LCD_PIC_INSTALL2,   /* 安装过程图片2 */
    LCD_PIC_INSTALL3,   /* 安装过程图片3 */
    LCD_PIC_INSTALL4,   /* 安装过程图片4 */
    LCD_PIC_INSTALL5,   /* 安装过程图片5 */
    LCD_PIC_INSTALL6,   /* 安装过程图片6 */
    LCD_PIC_INSTALL7,   /* 安装过程图片7 */
    LCD_PIC_INSTALL8,   /* 安装过程图片8 */
    LCD_PIC_INSTALL9,   /* 安装过程图片9 */
    LCD_PIC_INSTALL10,  /* 安装过程图片10 */
    LCD_PIC_INSTALL11,  /* 安装过程图片11 */

    LED_ATTR_ONOFF,     /* LED开关属性路径 */
    LED_ATTR_BRIGHT,    /* LED亮度属性路径 */
    LED_ATTR_DELAY_ON,  /* LED DELAY_ON属性路径 */
    LED_ATTR_DELAY_OFF, /* LED DELAY_OFF属性路径 */

    LED_SIGNAL1_ATTR_ONOFF,
    LED_SIGNAL2_ATTR_ONOFF,
    LED_SIGNAL3_ATTR_ONOFF,
    LED_MODE_RED_ATTR_ONOFF,
    LED_MODE_GREEN_ATTR_ONOFF,
    LED_MODE_BLUE_ATTR_ONOFF,

    LED_LTE_RED_ATTR_ONOFF,
    LED_LTE_RED_ATTR_DELAY_ON,
    LED_LTE_RED_ATTR_DELAY_OFF,
    LED_LTE_GREEN_ATTR_ONOFF,
    LED_LTE_GREEN_ATTR_DELAY_ON,
    LED_LTE_GREEN_ATTR_DELAY_OFF,
    LED_LTE_BLUE_ATTR_ONOFF,
    LED_LTE_BLUE_ATTR_DELAY_ON,
    LED_LTE_BLUE_ATTR_DELAY_OFF,

    LED_BAT_RED_ATTR_ONOFF,
    LED_BAT_GREEN_ATTR_ONOFF,
    LED_BAT_GREEN_ATTR_DELAY_ON,
    LED_BAT_GREEN_ATTR_DELAY_OFF,

    LED_POWER_GREEN_ATTR_ONOFF,
    LED_POWER_GREEN_ATTR_TRIGGER,
    LED_POWER_GREEN_ATTR_DELAY_ON,
    LED_POWER_GREEN_ATTR_DELAY_OFF,
    LED_POWER_RED_ATTR_ONOFF,
    LED_WIFI_GREEN_ATTR_ONOFF,
    LED_SIM_LED_GREEN_ATTR_ONOFF,
    LED_SIM_LED_RED_ATTR_ONOFF,
    LED_STATUS_GREEN_ATTR_ONOFF,
    LED_STATUS_GREEN_ATTR_TRIGGER,
    LED_STATUS_GREEN_ATTR_DELAY_ON,
    LED_STATUS_GREEN_ATTR_DELAY_OFF,
    LED_SIGNAL1_RED_ATTR_ONOFF,
    LED_SIGNAL1_BLUE_ATTR_ONOFF,
    LED_SIGNAL2_BLUE_ATTR_ONOFF,
    LED_SIGNAL3_BLUE_ATTR_ONOFF,

    LED_SIGNAL4_ATTR_ONOFF,
    LED_SIGNAL5_ATTR_ONOFF,
    LED_POWER_WHITE_ATTR_ONOFF,
    LED_WIFI_WHITE_ATTR_ONOFF,
    LED_LAN_WHITE_ATTR_ONOFF,
    LED_MSG_GREEN_ATTR_ONOFF,
    LED_MSG_GREEN_ATTR_DELAY_ON,
    LED_MSG_GREEN_ATTR_DELAY_OFF,
    LED_4G_GREEN_ATTR_ONOFF,
    LED_4G_GREEN_ATTR_DELAY_ON,
    LED_4G_GREEN_ATTR_DELAY_OFF,
}show_path_t;

/******************************************************************************
  2 模块私有 (全局变量) 定义区:
******************************************************************************/

/* 各形态产品ID命名
    E5类 touch E5：BV7R5E
         通用E5(LED)：BV7R5EU
         通用E5(LCD)：BV7R5EC
    CPE类：BV7R5C
    hilink： BV7R5HS
    stick： BV7R5HS
    wingle: BV7R5W
 */
/*平台标识，产品形态，硬件版本主ID()，硬件版本次ID,平台名称，对内产品名称，升级ID*/
/* 本次新增产品形态名称,如MRE5,RE5,NE5,HILINK,CPE,SLU,ALL等 */
/*  hilink产品 -> HILINK
    非裁剪版webui E5 -> RE5
    裁剪版webui E5 -> MRE5
    ndis E5 ->　NE5
    wingle产品 ->  RE5
    cpe产品 -> CPE
    solution产品 -> SLU
*/
/*  debug版本和release版本使用宏定义区分,用来在TA版本之后修改升级ID进行区别
    产品初始化配置时需要同时设置两处*/
#if (FEATURE_ON == MBB_BUILD_DEBUG)
/*debug版本升级信息*/
STATIC product_info_t product_info_st[] =
{
    {DLOAD_BALONG, DLOAD_E5,  0X0, 0X01, "V7R22", "E5785Lh-92a",  "E5785",  "NE5"},/* E5785Lh-92a */
    {DLOAD_BALONG, DLOAD_E5,  0X0, 0X17, "V7R22", "E5783h-92a",  "E5785",  "NE5"},/* E5783h-92a */
    {DLOAD_BALONG, DLOAD_CPE, 0X4, 0X21, "V7R22", "B520s-93a",  "B520",  "CPE"},/*B520s-93a*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X00, "V7R22", "ME919Bs-127a", "ME919Bs", "SLU"},/*ME919Bs-127a A版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X01, "V7R22", "ME919Bs-127a", "ME919Bs", "SLU"},/*ME919Bs-127a B版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X02, "V7R22", "ME919Bs-127a", "ME919Bs", "SLU"},/*ME919Bs-127a C版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X03, "V7R22", "ME919Bs-127a", "ME919Bs", "SLU"},/*ME919Bs-127a D版本*/

    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X04, "V7R22", "ME919Bs-567a", "ME919Bs", "SLU"},/*ME919Bs-567a A版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X05, "V7R22", "ME919Bs-567a", "ME919Bs", "SLU"},/*ME919Bs-567a B版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X06, "V7R22", "ME919Bs-567a", "ME919Bs", "SLU"},/*ME919Bs-567a C版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X07, "V7R22", "ME919Bs-567a", "ME919Bs", "SLU"},/*ME919Bs-567a D版本*/

    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X08, "V7R22", "ME919Bs-823a", "ME919Bs", "SLU"},/*ME919Bs-823a A版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X09, "V7R22", "ME919Bs-823a", "ME919Bs", "SLU"},/*ME919Bs-823a B版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X10, "V7R22", "ME919Bs-823a", "ME919Bs", "SLU"},/*ME919Bs-823a C版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X11, "V7R22", "ME919Bs-823a", "ME919Bs", "SLU"},/*ME919Bs-823a D版本*/

    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X12, "V7R22", "ME919Bs-727a", "ME919Bs", "SLU"},/*ME919Bs-727a A版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X13, "V7R22", "ME919Bs-727a", "ME919Bs", "SLU"},/*ME919Bs-727a B版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X14, "V7R22", "ME919Bs-727a", "ME919Bs", "SLU"},/*ME919Bs-727a C版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X15, "V7R22", "ME919Bs-727a", "ME919Bs", "SLU"},/*ME919Bs-727a D版本*/

    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X28, "V7R22", "MU809Bs-2",    "ME919Bs", "SLU"},/*MU809Bs-2 A版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X29, "V7R22", "MU809Bs-2",    "ME919Bs", "SLU"},/*MU809Bs-2 B版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X30, "V7R22", "MU809Bs-2",    "ME919Bs", "SLU"},/*MU809Bs-2 C版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X31, "V7R22", "MU809Bs-2",    "ME919Bs", "SLU"},/*MU809Bs-2 D版本*/

    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X16, "V7R22", "ME909Bs-566N", "ME909Bs-123N", "SLU"},/*ME909Bs-566N A版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X17, "V7R22", "ME909Bs-566N", "ME909Bs-123N", "SLU"},/*ME909Bs-566N B版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X18, "V7R22", "ME909Bs-566N", "ME909Bs-123N", "SLU"},/*ME909Bs-566N C版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X19, "V7R22", "ME909Bs-566N", "ME909Bs-123N", "SLU"},/*ME909Bs-566N D版本*/

    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X20, "V7R22", "ME909Bs-123N", "ME909Bs-123N", "SLU"},/*ME909Bs-123N A版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X21, "V7R22", "ME909Bs-123N", "ME909Bs-123N", "SLU"},/*ME909Bs-123N B版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X22, "V7R22", "ME909Bs-123N", "ME909Bs-123N", "SLU"},/*ME909Bs-123N C版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X23, "V7R22", "ME909Bs-123N", "ME909Bs-123N", "SLU"},/*ME909Bs-123N D版本*/

    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X24, "V7R22", "ME909Bs-827N", "ME909Bs-123N", "SLU"},/*ME909Bs-827N A版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X25, "V7R22", "ME909Bs-827N", "ME909Bs-123N", "SLU"},/*ME909Bs-827N B版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X26, "V7R22", "ME909Bs-827N", "ME909Bs-123N", "SLU"},/*ME909Bs-827N C版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X27, "V7R22", "ME909Bs-827N", "ME909Bs-123N", "SLU"},/*ME909Bs-827N D版本*/

    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X32, "V7R22", "ME919Bs-127bN", "ME909Bs-123N", "SLU"},/*ME919Bs-127bN A版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X33, "V7R22", "ME919Bs-127bN", "ME909Bs-123N", "SLU"},/*ME909Bs-127bN B版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X34, "V7R22", "ME919Bs-127bN", "ME909Bs-123N", "SLU"},/*ME909Bs-127bN C版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X35, "V7R22", "ME919Bs-127bN", "ME909Bs-123N", "SLU"},/*ME909Bs-127bN D版本*/

    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X36, "V7R22", "ME919Bs-567bN", "ME909Bs-123N", "SLU"},/*ME919Bs-567bN A版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X37, "V7R22", "ME919Bs-567bN", "ME909Bs-123N", "SLU"},/*ME919Bs-567bN B版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X38, "V7R22", "ME919Bs-567bN", "ME909Bs-123N", "SLU"},/*ME919Bs-567bN C版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X39, "V7R22", "ME919Bs-567bN", "ME909Bs-123N", "SLU"},/*ME919Bs-567bN D版本*/

    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X40, "V7R22", "ME919Bs-821bN", "ME909Bs-123N", "SLU"},/*ME919Bs-821bN A版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X41, "V7R22", "ME919Bs-821bN", "ME909Bs-123N", "SLU"},/*ME919Bs-821bN B版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X42, "V7R22", "ME919Bs-821bN", "ME909Bs-123N", "SLU"},/*ME919Bs-821bN C版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X43, "V7R22", "ME919Bs-821bN", "ME909Bs-123N", "SLU"},/*ME919Bs-821bN D版本*/

    {DLOAD_BALONG, DLOAD_E5,  0X0, 0X05, "V7R22", "E5787Ph-92a",  "E5787",  "NE5"},/* E5787Ph-92a*/
    {DLOAD_BALONG, DLOAD_E5,  0X0, 0X03, "V7R22", "E5785Lh-22c",  "E5785B",  "NE5"},/* E5785Lh-22c */
    {DLOAD_BALONG, DLOAD_E5,  0X0, 0X23, "V7R22", "R227h",  "R227",  "NE5"},/* R227 */
    {DLOAD_BALONG, DLOAD_E5,  0X0, 0X11, "V7R22", "E5787Ph-67a",  "E5787B",  "NE5"},/* E5787Ph-67a */
    {DLOAD_BALONG, DLOAD_E5,  0X0, 0X15, "V7R22", "E5785Lh-67a",  "E5785L",  "NE5"},/* E5785Lh-67a */
    {DLOAD_BALONG, DLOAD_CPE, 0X4, 0X24, "V7R22", "B525s-23a",  "B525",  "CPE"},/*B525s-23a*/
    {DLOAD_BALONG, DLOAD_CPE, 0X4, 0X26, "V7R22", "B528s-23a",  "B528",  "CPE"},/*B528s-23a*/
    {DLOAD_BALONG, DLOAD_CPE, 0X4, 0X27, "V7R22", "B529s-23a",  "B529",  "CPE"},/*B529s-23a*/
    {DLOAD_BALONG, DLOAD_E5,  0X0, 0X07, "V7R22", "E5785Ch-22c",  "E5785C",  "NE5"},/* E5785Ch-22c */
    {DLOAD_BALONG, DLOAD_CPE, 0X4, 0X22, "V7R22", "B525s-95a",  "B525",  "CPE"},/*B525s-95a*/
    {DLOAD_BALONG, DLOAD_E5,  0X0, 0X21, "V7R22", "E5785Lh-23c",  "E5785",  "NE5"},/* E5785Lh-23c */
    {DLOAD_BALONG, DLOAD_CPE, 0X4, 0X25, "V7R22", "B525s-65a",  "B525",  "CPE"},/* B525s-65a */
    {DLOAD_BALONG, DLOAD_E5,  0X0, 0X13, "V7R22", "E5885Ls-93a",  "E5885",  "NE5"},/* E5885Ls-93a */
};
#else
STATIC product_info_t product_info_st[] =
{
    {DLOAD_BALONG, DLOAD_E5,  0X0, 0X01, "V7R22", "E5785Lh-92a",  "E5785__0",  "NE5"},/* E5785Lh-92a */
    {DLOAD_BALONG, DLOAD_E5,  0X0, 0X17, "V7R22", "E5783h-92a",  "E5785__0",  "NE5"},/* E5783h-92a */
    {DLOAD_BALONG, DLOAD_CPE, 0X4, 0X21, "V7R22", "B520s-93a",  "B520__0",  "CPE"},/*B520s-93a*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X00, "V7R22", "ME919Bs-127a", "ME919Bs", "SLU"},/*ME919Bs-127a A版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X01, "V7R22", "ME919Bs-127a", "ME919Bs", "SLU"},/*ME919Bs-127a B版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X02, "V7R22", "ME919Bs-127a", "ME919Bs", "SLU"},/*ME919Bs-127a C版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X03, "V7R22", "ME919Bs-127a", "ME919Bs", "SLU"},/*ME919Bs-127a D版本*/

    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X04, "V7R22", "ME919Bs-567a", "ME919Bs", "SLU"},/*ME919Bs-567a A版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X05, "V7R22", "ME919Bs-567a", "ME919Bs", "SLU"},/*ME919Bs-567a B版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X06, "V7R22", "ME919Bs-567a", "ME919Bs", "SLU"},/*ME919Bs-567a C版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X07, "V7R22", "ME919Bs-567a", "ME919Bs", "SLU"},/*ME919Bs-567a D版本*/

    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X08, "V7R22", "ME919Bs-823a", "ME919Bs", "SLU"},/*ME919Bs-823a A版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X09, "V7R22", "ME919Bs-823a", "ME919Bs", "SLU"},/*ME919Bs-823a B版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X10, "V7R22", "ME919Bs-823a", "ME919Bs", "SLU"},/*ME919Bs-823a C版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X11, "V7R22", "ME919Bs-823a", "ME919Bs", "SLU"},/*ME919Bs-823a D版本*/

    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X12, "V7R22", "ME919Bs-727a", "ME919Bs", "SLU"},/*ME919Bs-727a A版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X13, "V7R22", "ME919Bs-727a", "ME919Bs", "SLU"},/*ME919Bs-727a B版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X14, "V7R22", "ME919Bs-727a", "ME919Bs", "SLU"},/*ME919Bs-727a C版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X15, "V7R22", "ME919Bs-727a", "ME919Bs", "SLU"},/*ME919Bs-727a D版本*/

    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X28, "V7R22", "MU809Bs-2",    "ME919Bs", "SLU"},/*MU809Bs-2 A版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X29, "V7R22", "MU809Bs-2",    "ME919Bs", "SLU"},/*MU809Bs-2 B版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X30, "V7R22", "MU809Bs-2",    "ME919Bs", "SLU"},/*MU809Bs-2 C版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X31, "V7R22", "MU809Bs-2",    "ME919Bs", "SLU"},/*MU809Bs-2 D版本*/

    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X16, "V7R22", "ME909Bs-566N", "ME909Bs-123N", "SLU"},/*ME909Bs-566N A版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X17, "V7R22", "ME909Bs-566N", "ME909Bs-123N", "SLU"},/*ME909Bs-566N B版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X18, "V7R22", "ME909Bs-566N", "ME909Bs-123N", "SLU"},/*ME909Bs-566N C版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X19, "V7R22", "ME909Bs-566N", "ME909Bs-123N", "SLU"},/*ME909Bs-566N D版本*/

    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X20, "V7R22", "ME909Bs-123N", "ME909Bs-123N", "SLU"},/*ME909Bs-123N A版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X21, "V7R22", "ME909Bs-123N", "ME909Bs-123N", "SLU"},/*ME909Bs-123N B版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X22, "V7R22", "ME909Bs-123N", "ME909Bs-123N", "SLU"},/*ME909Bs-123N C版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X23, "V7R22", "ME909Bs-123N", "ME909Bs-123N", "SLU"},/*ME909Bs-123N D版本*/

    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X24, "V7R22", "ME909Bs-827N", "ME909Bs-123N", "SLU"},/*ME909Bs-827N A版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X25, "V7R22", "ME909Bs-827N", "ME909Bs-123N", "SLU"},/*ME909Bs-827N B版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X26, "V7R22", "ME909Bs-827N", "ME909Bs-123N", "SLU"},/*ME909Bs-827N C版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X27, "V7R22", "ME909Bs-827N", "ME909Bs-123N", "SLU"},/*ME909Bs-827N D版本*/

    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X32, "V7R22", "ME919Bs-127bN", "ME909Bs-123N", "SLU"},/*ME919Bs-127bN A版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X33, "V7R22", "ME919Bs-127bN", "ME909Bs-123N", "SLU"},/*ME909Bs-127bN B版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X34, "V7R22", "ME919Bs-127bN", "ME909Bs-123N", "SLU"},/*ME909Bs-127bN C版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X35, "V7R22", "ME919Bs-127bN", "ME909Bs-123N", "SLU"},/*ME909Bs-127bN D版本*/

    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X36, "V7R22", "ME919Bs-567bN", "ME909Bs-123N", "SLU"},/*ME919Bs-567bN A版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X37, "V7R22", "ME919Bs-567bN", "ME909Bs-123N", "SLU"},/*ME919Bs-567bN B版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X38, "V7R22", "ME919Bs-567bN", "ME909Bs-123N", "SLU"},/*ME919Bs-567bN C版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X39, "V7R22", "ME919Bs-567bN", "ME909Bs-123N", "SLU"},/*ME919Bs-567bN D版本*/

    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X40, "V7R22", "ME919Bs-821bN", "ME909Bs-123N", "SLU"},/*ME919Bs-821bN A版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X41, "V7R22", "ME919Bs-821bN", "ME909Bs-123N", "SLU"},/*ME919Bs-821bN B版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X42, "V7R22", "ME919Bs-821bN", "ME909Bs-123N", "SLU"},/*ME919Bs-821bN C版本*/
    {DLOAD_BALONG, DLOAD_TELEMATIC, 0X5, 0X43, "V7R22", "ME919Bs-821bN", "ME909Bs-123N", "SLU"},/*ME919Bs-821bN D版本*/

    {DLOAD_BALONG, DLOAD_E5,  0X0, 0X05, "V7R22", "E5787Ph-92a",  "E5787__0",  "NE5"},/* E5787Ph-92a */
    {DLOAD_BALONG, DLOAD_E5,  0X0, 0X03, "V7R22", "E5785Lh-22c",  "E5785B__0",  "NE5"},/* E5785Lh-22c */
    {DLOAD_BALONG, DLOAD_E5,  0X0, 0X23, "V7R22", "R227h",  "R227",  "NE5"},/* R227h */
    {DLOAD_BALONG, DLOAD_E5,  0X0, 0X11, "V7R22", "E5787Ph-67a",  "E5787B",  "NE5"},/* E5787Ph-67a */
    {DLOAD_BALONG, DLOAD_E5,  0X0, 0X15, "V7R22", "E5785Lh-67a",  "E5785L__0",  "NE5"},/* E5785Lh-67a */
    {DLOAD_BALONG, DLOAD_CPE, 0X4, 0X24, "V7R22", "B525s-23a",  "B525__0",  "CPE"},/*B525s-23a*/
    {DLOAD_BALONG, DLOAD_CPE, 0X4, 0X26, "V7R22", "B528s-23a",  "B528__0",  "CPE"},/*B528s-23a*/
    {DLOAD_BALONG, DLOAD_CPE, 0X4, 0X27, "V7R22", "B529s-23a",  "B529__0",  "CPE"},/*B529s-23a*/
    {DLOAD_BALONG, DLOAD_E5,  0X0, 0X07, "V7R22", "E5785Ch-22c",  "E5785C",  "NE5"},/* E5785Ch-22c */
    {DLOAD_BALONG, DLOAD_CPE, 0X4, 0X22, "V7R22", "B525s-95a",  "B525__0",  "CPE"},/*B525s-95a*/
    {DLOAD_BALONG, DLOAD_E5,  0X0, 0X21, "V7R22", "E5785Lh-23c",  "E5785__0",  "NE5"},/* E5785Lh-23c */
    {DLOAD_BALONG, DLOAD_CPE, 0X4, 0X25, "V7R22", "B525s-65a",  "B525__0",  "CPE"},/* B525s-65a */
    {DLOAD_BALONG, DLOAD_E5,  0X0, 0X13, "V7R22", "E5885Ls-93a",  "E5885__0",  "NE5"},/* E5885Ls-93a */
};
#endif

/* 升级特性配置表
   产品硬件主ID, 产品硬件次ID, USB升级, SD升级
   在线升级, 安全升级, HOTA升级, FOTA升级, FOTA升级相关信息字段
   安全升级v1.3方案相关信息, m3boot双备份标志, 预留 */
STATIC dload_feature_t dload_feature_st[] =
{
    {0X0, 0X01, TRUE,  FALSE, TRUE, TRUE, FALSE, FALSE, {FALSE}, {TRUE, TRUE, TRUE, TRUE}, TRUE, FALSE, FALSE, FALSE, {FALSE}},      /* E5785Lh-92a */
    {0X4, 0X21, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, {FALSE}, {TRUE, TRUE, TRUE, TRUE}, TRUE, FALSE, FALSE, FALSE, {FALSE}},      /* B520s-93a */
    {0X5, 0X00, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* ME919Bs-127a A版本*/
    {0X5, 0X01, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* ME919Bs-127a B版本*/
    {0X5, 0X02, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* ME919Bs-127a C版本*/
    {0X5, 0X03, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* ME919Bs-127a D版本*/

    {0X5, 0X04, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* ME919Bs-567a A版本*/
    {0X5, 0X05, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* ME919Bs-567a B版本*/
    {0X5, 0X06, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* ME919Bs-567a C版本*/
    {0X5, 0X07, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* ME919Bs-567a D版本*/

    {0X5, 0X08, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* ME919Bs-823a A版本*/
    {0X5, 0X09, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* ME919Bs-823a B版本*/
    {0X5, 0X10, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* ME919Bs-823a C版本*/
    {0X5, 0X11, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* ME919Bs-823a D版本*/

    {0X5, 0X12, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* ME919Bs-727a A版本*/
    {0X5, 0X13, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* ME919Bs-727a B版本*/
    {0X5, 0X14, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* ME919Bs-727a C版本*/
    {0X5, 0X15, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* ME919Bs-727a D版本*/

    {0X5, 0X28, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* MU809Bs-2 A版本*/
    {0X5, 0X29, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* MU809Bs-2 B版本*/
    {0X5, 0X30, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* MU809Bs-2 C版本*/
    {0X5, 0X31, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* MU809Bs-2 D版本*/

    {0X5, 0X16, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, FALSE, FALSE, TRUE, {FALSE}}, /* ME909Bs-566N A版本*/
    {0X5, 0X17, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, FALSE, FALSE, TRUE, {FALSE}}, /* ME909Bs-566N B版本*/
    {0X5, 0X18, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, FALSE, FALSE, TRUE, {FALSE}}, /* ME909Bs-566N C版本*/
    {0X5, 0X19, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, FALSE, FALSE, TRUE, {FALSE}}, /* ME909Bs-566N D版本*/

    {0X5, 0X20, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, FALSE, FALSE, TRUE,  {FALSE}}, /* ME909Bs-123N A版本*/
    {0X5, 0X21, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, FALSE, FALSE, TRUE,  {FALSE}}, /* ME909Bs-123N B版本*/
    {0X5, 0X22, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, FALSE, FALSE, TRUE,  {FALSE}}, /* ME909Bs-123N C版本*/
    {0X5, 0X23, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, FALSE, FALSE, TRUE,  {FALSE}}, /* ME909Bs-123N D版本*/

    {0X5, 0X24, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, FALSE, FALSE, TRUE,  {FALSE}}, /* ME909Bs-827N A版本*/
    {0X5, 0X25, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, FALSE, FALSE, TRUE,  {FALSE}}, /* ME909Bs-827N B版本*/
    {0X5, 0X26, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, FALSE, FALSE, TRUE,  {FALSE}}, /* ME909Bs-827N C版本*/
    {0X5, 0X27, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, FALSE, FALSE, TRUE,  {FALSE}}, /* ME909Bs-827N D版本*/

    {0X5, 0X32, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* ME919Bs-127bN A版本*/
    {0X5, 0X33, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* ME919Bs-127bN B版本*/
    {0X5, 0X34, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* ME919Bs-127bN C版本*/
    {0X5, 0X35, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* ME919Bs-127bN D版本*/

    {0X5, 0X36, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* ME919Bs-567bN A版本*/
    {0X5, 0X37, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* ME919Bs-567bN B版本*/
    {0X5, 0X38, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* ME919Bs-567bN C版本*/
    {0X5, 0X39, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* ME919Bs-567bN D版本*/

    {0X5, 0X40, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* ME919Bs-821bN A版本*/
    {0X5, 0X41, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* ME919Bs-821bN B版本*/
    {0X5, 0X42, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* ME919Bs-821bN C版本*/
    {0X5, 0X43, TRUE,  FALSE, TRUE, TRUE, FALSE, TRUE, \
        {{FOTA_FSLIST_BALONG_COMMON}, {FOTA_FSTYPE_BALONG_COMMON}, 0x2800000, {FALSE}}, {TRUE, TRUE, TRUE, TRUE}, TRUE, TRUE, FALSE, TRUE, {FALSE}}, /* ME919Bs-821bN D版本*/

    {0X0, 0X05, TRUE,  FALSE, TRUE, TRUE, FALSE, FALSE, {FALSE}, {TRUE, TRUE, TRUE, TRUE}, TRUE, FALSE, FALSE, FALSE, {FALSE}},      /* E5787Ph-92a */
    {0X0, 0X03, TRUE,  FALSE, TRUE, TRUE, FALSE, FALSE, {FALSE}, {TRUE, TRUE, TRUE, TRUE}, TRUE, FALSE, FALSE, FALSE, {FALSE}},      /* E5785Lh-22c */
    {0X0, 0X23, TRUE,  FALSE, TRUE, TRUE, FALSE, FALSE, {FALSE}, {TRUE, TRUE, TRUE, TRUE}, TRUE, FALSE, FALSE, FALSE, {FALSE}},      /* R227 */
    {0X0, 0X11, TRUE,  FALSE, TRUE, TRUE, FALSE, FALSE, {FALSE}, {TRUE, TRUE, TRUE, TRUE}, TRUE, FALSE, FALSE, FALSE, {FALSE}},      /* E5787Ph-67a */
    {0X0, 0X15, TRUE,  FALSE, TRUE, TRUE, FALSE, FALSE, {FALSE}, {TRUE, TRUE, TRUE, TRUE}, TRUE, FALSE, FALSE, FALSE, {FALSE}},      /* E5785Lh-67a */
    {0X4, 0X24, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, {FALSE}, {TRUE, TRUE, TRUE, TRUE}, TRUE, FALSE, FALSE, FALSE, {FALSE}},      /* B525s-23a */
    {0X4, 0X26, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, {FALSE}, {TRUE, TRUE, TRUE, TRUE}, TRUE, FALSE, FALSE, FALSE, {FALSE}},      /* B528s-23a */
    {0X4, 0X27, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, {FALSE}, {TRUE, TRUE, TRUE, TRUE}, TRUE, FALSE, FALSE, FALSE, {FALSE}},      /* B529s-23a */
    {0X0, 0X07, TRUE,  FALSE, TRUE, TRUE, FALSE, FALSE, {FALSE}, {TRUE, TRUE, TRUE, TRUE}, TRUE, FALSE, FALSE, FALSE, {FALSE}},      /* E5785Ch-22c */
    {0X4, 0X22, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, {FALSE}, {TRUE, TRUE, TRUE, TRUE}, TRUE, FALSE, FALSE, FALSE, {FALSE}},      /* B525s-95a */
    {0X0, 0X21, TRUE,  FALSE, TRUE, TRUE, FALSE, FALSE, {FALSE}, {TRUE, TRUE, TRUE, TRUE}, TRUE, FALSE, FALSE, FALSE, {FALSE}},      /* E5785Lh-23c */
    {0X0, 0X17, TRUE,  FALSE, TRUE, TRUE, FALSE, FALSE, {FALSE}, {TRUE, TRUE, TRUE, TRUE}, TRUE, FALSE, FALSE, FALSE, {FALSE}},      /* E5783h-92a */
    {0X4, 0X25, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, {FALSE}, {TRUE, TRUE, TRUE, TRUE}, TRUE, FALSE, FALSE, FALSE, {FALSE}},      /* B525s-65a */
    {0X0, 0X13, TRUE,  FALSE, TRUE, TRUE, FALSE, FALSE, {FALSE}, {TRUE, TRUE, TRUE, TRUE}, TRUE, FALSE, FALSE, FALSE, {FALSE}},      /* E5885Ls-93a */
};


/* 根据产品升级状态亮灯 规格配置*/
#if (FEATURE_ON == MBB_DLOAD_MCPEUP)
#define SHOW_YES_DELAY         (200000) /*延时200ms*/
STATIC path_info_t pathinfo_st[] =
{
    {LED_POWER_WHITE_ATTR_ONOFF,      "/sys/class/leds/power_led:white/brightness"},
    {LED_MODE_RED_ATTR_ONOFF,         "/sys/class/leds/mode_led:red/brightness"},
    {LED_MODE_GREEN_ATTR_ONOFF,       "/sys/class/leds/mode_led:green/brightness"},
    {LED_MODE_BLUE_ATTR_ONOFF,        "/sys/class/leds/mode_led:blue/brightness"},
    {LED_LAN_WHITE_ATTR_ONOFF,        "/sys/class/leds/lan_led:white/brightness"},
    {LED_WIFI_WHITE_ATTR_ONOFF,       "/sys/class/leds/wifi_led:white/brightness"},
    {LED_SIGNAL1_ATTR_ONOFF,          "/sys/class/leds/signal1_led:white/brightness"},
    {LED_SIGNAL2_ATTR_ONOFF,          "/sys/class/leds/signal2_led:white/brightness"},
    {LED_SIGNAL3_ATTR_ONOFF,          "/sys/class/leds/signal3_led:white/brightness"},
    {LED_SIGNAL4_ATTR_ONOFF,          "/sys/class/leds/signal4_led:white/brightness"},
    {LED_SIGNAL5_ATTR_ONOFF,          "/sys/class/leds/signal5_led:white/brightness"},
};

STATIC upstate_info_t upstateinfo_st[] =
{
    /* LED显示配置 */
    /* 通用运行状态显示序列 */
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "255"},                        SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_POWER_WHITE_ATTR_ONOFF}, SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_MODE_RED_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_MODE_GREEN_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "255"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_MODE_BLUE_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_WIFI_WHITE_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_LAN_WHITE_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_SIGNAL1_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "255"},                 SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_SIGNAL2_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "255"},                 SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_SIGNAL3_ATTR_ONOFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_SIGNAL5_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_SIGNAL5_ATTR_ONOFF},       SHOW_NOT_DELAY},

    {DLOAD_STATE_AUTOUG_RUNNING,   LED_READ,   {.str_value  = "255"},                        SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_WRITE,  {.path_index = LED_POWER_WHITE_ATTR_ONOFF}, SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_WRITE,  {.path_index = LED_MODE_RED_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_WRITE,  {.path_index = LED_MODE_GREEN_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_READ,   {.str_value  = "255"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_WRITE,  {.path_index = LED_MODE_BLUE_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_WRITE,  {.path_index = LED_WIFI_WHITE_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_WRITE,  {.path_index = LED_LAN_WHITE_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_WRITE,  {.path_index = LED_SIGNAL1_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_READ,   {.str_value  = "255"},                 SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_WRITE,  {.path_index = LED_SIGNAL2_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_READ,   {.str_value  = "255"},                 SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_WRITE,  {.path_index = LED_SIGNAL3_ATTR_ONOFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_WRITE,  {.path_index = LED_SIGNAL5_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_WRITE,  {.path_index = LED_SIGNAL5_ATTR_ONOFF},       SHOW_NOT_DELAY},

    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "255"},                        SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_POWER_WHITE_ATTR_ONOFF}, SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "255"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_MODE_RED_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "255"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_MODE_GREEN_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "255"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_MODE_BLUE_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_WIFI_WHITE_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_LAN_WHITE_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_SIGNAL1_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "255"},                 SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_SIGNAL2_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "255"},                 SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_SIGNAL3_ATTR_ONOFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_SIGNAL5_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_SIGNAL5_ATTR_ONOFF},       SHOW_NOT_DELAY},

    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "255"},                        SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_POWER_WHITE_ATTR_ONOFF}, SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "255"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_MODE_RED_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_MODE_GREEN_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_MODE_BLUE_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_WIFI_WHITE_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_LAN_WHITE_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_SIGNAL1_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "255"},                 SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_SIGNAL2_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "255"},                 SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_SIGNAL3_ATTR_ONOFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_SIGNAL5_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_SIGNAL5_ATTR_ONOFF},       SHOW_NOT_DELAY},

    {DLOAD_STATE_FAIL,   LED_READ,   {.str_value  = "255"},                        SHOW_NOT_DELAY},
    {DLOAD_STATE_FAIL,   LED_WRITE,  {.path_index = LED_POWER_WHITE_ATTR_ONOFF}, SHOW_NOT_DELAY},
    {DLOAD_STATE_FAIL,   LED_READ,   {.str_value  = "255"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_FAIL,   LED_WRITE,  {.path_index = LED_MODE_RED_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_FAIL,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_FAIL,   LED_WRITE,  {.path_index = LED_MODE_GREEN_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_FAIL,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_FAIL,   LED_WRITE,  {.path_index = LED_MODE_BLUE_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_FAIL,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_FAIL,   LED_WRITE,  {.path_index = LED_WIFI_WHITE_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_FAIL,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_FAIL,   LED_WRITE,  {.path_index = LED_LAN_WHITE_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_FAIL,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_FAIL,   LED_WRITE,  {.path_index = LED_SIGNAL1_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_FAIL,   LED_READ,   {.str_value  = "255"},                 SHOW_NOT_DELAY},
    {DLOAD_STATE_FAIL,   LED_WRITE,  {.path_index = LED_SIGNAL2_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_FAIL,   LED_READ,   {.str_value  = "255"},                 SHOW_NOT_DELAY},
    {DLOAD_STATE_FAIL,   LED_WRITE,  {.path_index = LED_SIGNAL3_ATTR_ONOFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_FAIL,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_FAIL,   LED_WRITE,  {.path_index = LED_SIGNAL5_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_FAIL,   LED_READ,   {.str_value  = "0"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_FAIL,   LED_WRITE,  {.path_index = LED_SIGNAL5_ATTR_ONOFF},       SHOW_NOT_DELAY},
};
#elif (FEATURE_ON == MBB_DLOAD_STICK || FEATURE_ON == MBB_DLOAD_HILINK || FEATURE_ON == MBB_DLOAD_WINGLE)
STATIC path_info_t pathinfo_st[] =
{
    {LED_LTE_GREEN_ATTR_ONOFF,       "/sys/class/leds/lte_led:green/trigger"},
    {LED_LTE_GREEN_ATTR_DELAY_ON,    "/sys/class/leds/lte_led:green/delay_on"},
    {LED_LTE_GREEN_ATTR_DELAY_OFF,   "/sys/class/leds/lte_led:green/delay_off"},

};

STATIC upstate_info_t upstateinfo_st[] =
{
    /* 空闲状态显示序列 */
    {DLOAD_STATE_NORMAL_IDLE,   LED_READ,   {.str_value  = "timer"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_ONOFF},        SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_READ,   {.str_value  = "100"},                           SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_OFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_READ,   {.str_value  = "100"},                           SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_ON},     SHOW_NOT_DELAY},

    /* 通用运行状态显示序列 */
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "timer"},                    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_ONOFF},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "100"},                        SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_OFF}, SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "100"},                        SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_ON},  SHOW_NOT_DELAY},

    /* 升级成功状态显示序列 */
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "timer"},                    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_ONOFF},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "100"},                        SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_OFF}, SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "100"},                        SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_ON},  SHOW_NOT_DELAY},

    /* 升级失败状态显示序列 */
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "timer"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_ONOFF},        SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "100"},                           SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_OFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "100"},                           SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_ON},     SHOW_NOT_DELAY},

};

STATIC path_info_t pathinfo_burn_st[] =
{
    {LED_LTE_GREEN_ATTR_ONOFF,       "/sys/class/leds/lte_led:green/trigger"},
    {LED_LTE_GREEN_ATTR_DELAY_ON,    "/sys/class/leds/lte_led:green/delay_on"},
    {LED_LTE_GREEN_ATTR_DELAY_OFF,   "/sys/class/leds/lte_led:green/delay_off"},
    {LED_LTE_BLUE_ATTR_ONOFF,        "/sys/class/leds/lte_led:blue/trigger"},
    {LED_LTE_BLUE_ATTR_DELAY_ON,     "/sys/class/leds/lte_led:blue/delay_on"},
    {LED_LTE_BLUE_ATTR_DELAY_OFF,    "/sys/class/leds/lte_led:blue/delay_off"},
    {LED_LTE_RED_ATTR_ONOFF,         "/sys/class/leds/lte_led:red/trigger"},
    {LED_LTE_RED_ATTR_DELAY_ON,      "/sys/class/leds/lte_led:red/delay_on"},
    {LED_LTE_RED_ATTR_DELAY_OFF,     "/sys/class/leds/lte_led:red/delay_off"},

};

STATIC upstate_info_t upstateinfo_burn_st[] =
{
    /* 空闲状态显示序列 */
    {DLOAD_STATE_NORMAL_IDLE,   LED_READ,   {.str_value  = "timer"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_ONOFF},        SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_READ,   {.str_value  = "100"},                           SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_OFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_READ,   {.str_value  = "100"},                           SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_ON},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_READ,   {.str_value  = "timer"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_WRITE,  {.path_index = LED_LTE_BLUE_ATTR_ONOFF},        SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_READ,   {.str_value  = "100"},                           SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_WRITE,  {.path_index = LED_LTE_BLUE_ATTR_DELAY_ON},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_READ,   {.str_value  = "100"},                           SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_WRITE,  {.path_index = LED_LTE_BLUE_ATTR_DELAY_OFF},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_READ,   {.str_value  = "timer"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_WRITE,  {.path_index = LED_LTE_RED_ATTR_ONOFF},        SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_READ,   {.str_value  = "100"},                           SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_WRITE,  {.path_index = LED_LTE_RED_ATTR_DELAY_ON},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_READ,   {.str_value  = "100"},                           SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_WRITE,  {.path_index = LED_LTE_RED_ATTR_DELAY_OFF},     SHOW_NOT_DELAY},

    /* 通用运行状态显示序列 */
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "timer"},                    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_ONOFF},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "100"},                        SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_OFF}, SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "100"},                        SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_ON},  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "timer"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_LTE_BLUE_ATTR_ONOFF},        SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "100"},                           SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_LTE_BLUE_ATTR_DELAY_ON},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "100"},                           SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_LTE_BLUE_ATTR_DELAY_OFF},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "timer"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_LTE_RED_ATTR_ONOFF},        SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "100"},                           SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_LTE_RED_ATTR_DELAY_ON},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "100"},                           SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_LTE_RED_ATTR_DELAY_OFF},     SHOW_NOT_DELAY},

    /* 升级成功状态显示序列 */
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "timer"},                    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_ONOFF},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "100"},                        SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_OFF}, SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "100"},                        SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_ON},  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "timer"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_LTE_BLUE_ATTR_ONOFF},        SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "100"},                           SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_LTE_BLUE_ATTR_DELAY_ON},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "100"},                           SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_LTE_BLUE_ATTR_DELAY_OFF},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "timer"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_LTE_RED_ATTR_ONOFF},        SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "100"},                           SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_LTE_RED_ATTR_DELAY_ON},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "100"},                           SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_LTE_RED_ATTR_DELAY_OFF},     SHOW_NOT_DELAY},

    /* 升级失败状态显示序列 */
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "timer"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_ONOFF},        SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "100"},                           SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_OFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "100"},                           SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_ON},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "timer"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_LTE_BLUE_ATTR_ONOFF},        SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "100"},                           SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_LTE_BLUE_ATTR_DELAY_ON},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "100"},                           SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_LTE_BLUE_ATTR_DELAY_OFF},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "timer"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_LTE_RED_ATTR_ONOFF},        SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "100"},                           SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_LTE_RED_ATTR_DELAY_ON},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "100"},                           SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_LTE_RED_ATTR_DELAY_OFF},     SHOW_NOT_DELAY},
};
#elif (FEATURE_ON == MBB_DLOAD_E5)
#if(FEATURE_ON == MBB_LED_LCD_UNIFORM)
#define SHOW_YES_DELAY         (1000000) /*延时1s*/
/*归一化方案后，需要在这里新增每个产品自己的pathinfo和upstateinfo*/
STATIC path_info_t pathinfo_st_E5785Lh_92a[] =
{
    {LCD_DEV_NAME,          "/dev/fb0"},
    {LCD_PIC_SUCCESS,       "/pic/%d_%d/upgrade_success"},
    {LCD_PIC_FAILED,        "/pic/%d_%d/upgrade_fail"},
    {LCD_PIC_AUTOUG,        "/pic/%d_%d/auto_update"},
    {LCD_PIC_LOWPOWER,      "/pic/%d_%d/lowpower"},
    {LCD_PIC_INSTALL0,      "/pic/%d_%d/installing_0"},
    {LCD_PIC_INSTALL1,      "/pic/%d_%d/installing_1"},
    {LCD_PIC_INSTALL2,      "/pic/%d_%d/installing_2"},
    {LCD_PIC_INSTALL3,      "/pic/%d_%d/installing_3"},
    {LCD_PIC_INSTALL4,      "/pic/%d_%d/installing_4"},
    {LCD_PIC_INSTALL5,      "/pic/%d_%d/installing_5"},
    {LCD_PIC_INSTALL6,      "/pic/%d_%d/installing_6"},
    {LCD_PIC_INSTALL7,      "/pic/%d_%d/installing_7"},
    {LCD_PIC_INSTALL8,      "/pic/%d_%d/installing_8"},
    {LCD_PIC_INSTALL9,      "/pic/%d_%d/installing_9"},
    {LCD_PIC_INSTALL10,     "/pic/%d_%d/installing_10"},
    {LCD_PIC_INSTALL11,     "/pic/%d_%d/installing_11"},
};

/* LCD 运行状态列表 */
STATIC upstate_info_t upstateinfo_st_E5785Lh_92a[] =
{
    /* LCD显示配置 */
    /* 空闲状态显示序列 */
    {DLOAD_STATE_NORMAL_IDLE,      LCD_READ,   {.path_index = LCD_PIC_INSTALL0},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,      LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},

    /* 通用运行状态显示序列 */
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL0},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL1},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL2},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL3},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL4},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL5},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL6},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL7},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL8},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL9},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL10},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL11},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},

    /* 在线升级运行状态显示序列 */
    {DLOAD_STATE_AUTOUG_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_AUTOUG},       SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},

    /* 低电状态显示序列 */
    {DLOAD_STATE_NORMAL_LOW_POWER, LCD_READ,   {.path_index = LCD_PIC_LOWPOWER},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_LOW_POWER, LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},

    /* 升级成功状态显示序列 */
    {DLOAD_STATE_NORMAL_SUCCESS,   LCD_READ,   {.path_index = LCD_PIC_SUCCESS},      SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},

    /* 升级失败状态显示序列 */
    {DLOAD_STATE_NORMAL_FAIL,      LCD_READ,   {.path_index = LCD_PIC_FAILED},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,      LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},

};
STATIC path_info_t pathinfo_st_E5873h_92a[] =
{
    {LED_LTE_GREEN_ATTR_ONOFF,       "/sys/class/leds/lte_led:green/trigger"},
    {LED_LTE_GREEN_ATTR_DELAY_ON,    "/sys/class/leds/lte_led:green/delay_on"},
    {LED_LTE_GREEN_ATTR_DELAY_OFF,   "/sys/class/leds/lte_led:green/delay_off"},
    {LED_BAT_GREEN_ATTR_ONOFF,       "/sys/class/leds/bat_led:green/trigger"},
    {LED_BAT_GREEN_ATTR_DELAY_ON,    "/sys/class/leds/bat_led:green/delay_on"},
    {LED_BAT_GREEN_ATTR_DELAY_OFF,   "/sys/class/leds/bat_led:green/delay_off"},
    {LED_4G_GREEN_ATTR_ONOFF,       "/sys/class/leds/4g_led:green/trigger"},
    {LED_4G_GREEN_ATTR_DELAY_ON,    "/sys/class/leds/4g_led:green/delay_on"},
    {LED_4G_GREEN_ATTR_DELAY_OFF,   "/sys/class/leds/4g_led:green/delay_off"},
};
STATIC upstate_info_t upstateinfo_st_E5783h_92a[] =
{
    /* 空闲状态显示序列 */
    {DLOAD_STATE_NORMAL_IDLE,   LED_READ,   {.str_value  = "timer"},                     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_ONOFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_OFF},SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_ON}, SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_READ,   {.str_value  = "timer"},                     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_WRITE,  {.path_index = LED_BAT_GREEN_ATTR_ONOFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_WRITE,  {.path_index = LED_BAT_GREEN_ATTR_DELAY_OFF},SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_WRITE,  {.path_index = LED_BAT_GREEN_ATTR_DELAY_ON}, SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_READ,   {.str_value  = "timer"},                     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_WRITE,  {.path_index = LED_4G_GREEN_ATTR_ONOFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_WRITE,  {.path_index = LED_4G_GREEN_ATTR_DELAY_OFF},SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_WRITE,  {.path_index = LED_4G_GREEN_ATTR_DELAY_ON}, SHOW_NOT_DELAY},

    /* 通用运行状态显示序列 */
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "timer"},                     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_ONOFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_OFF},SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_ON}, SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "timer"},                     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_BAT_GREEN_ATTR_ONOFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_BAT_GREEN_ATTR_DELAY_OFF},SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_BAT_GREEN_ATTR_DELAY_ON}, SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "timer"},                     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_4G_GREEN_ATTR_ONOFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_4G_GREEN_ATTR_DELAY_OFF},SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_4G_GREEN_ATTR_DELAY_ON}, SHOW_NOT_DELAY},


    /* 升级成功状态显示序列 */
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "timer"},                     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_ONOFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_OFF},SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_ON}, SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "timer"},                     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_BAT_GREEN_ATTR_ONOFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_BAT_GREEN_ATTR_DELAY_OFF},SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_BAT_GREEN_ATTR_DELAY_ON}, SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "timer"},                     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_4G_GREEN_ATTR_ONOFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_4G_GREEN_ATTR_DELAY_OFF},SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_4G_GREEN_ATTR_DELAY_ON}, SHOW_NOT_DELAY},


    /* 升级失败状态显示序列 */
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "timer"},                     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_ONOFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_OFF},SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_ON}, SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "timer"},                     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_BAT_GREEN_ATTR_ONOFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_BAT_GREEN_ATTR_DELAY_OFF},SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_BAT_GREEN_ATTR_DELAY_ON}, SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "timer"},                     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_4G_GREEN_ATTR_ONOFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_4G_GREEN_ATTR_DELAY_OFF},SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_4G_GREEN_ATTR_DELAY_ON}, SHOW_NOT_DELAY},
};
#else
#if (FEATURE_ON == MBB_DLOAD_LCD)
#define SHOW_YES_DELAY         (1000000) /*延时1s*/
STATIC path_info_t pathinfo_st[] =
{
    {LCD_DEV_NAME,          "/dev/fb0"},
    {LCD_PIC_SUCCESS,       "/pic/%d_%d/upgrade_success"},
    {LCD_PIC_FAILED,        "/pic/%d_%d/upgrade_fail"},
    {LCD_PIC_AUTOUG,        "/pic/%d_%d/auto_update"},
    {LCD_PIC_LOWPOWER,      "/pic/%d_%d/lowpower"},
    {LCD_PIC_INSTALL0,      "/pic/%d_%d/installing_0"},
    {LCD_PIC_INSTALL1,      "/pic/%d_%d/installing_1"},
    {LCD_PIC_INSTALL2,      "/pic/%d_%d/installing_2"},
    {LCD_PIC_INSTALL3,      "/pic/%d_%d/installing_3"},
    {LCD_PIC_INSTALL4,      "/pic/%d_%d/installing_4"},
    {LCD_PIC_INSTALL5,      "/pic/%d_%d/installing_5"},
    {LCD_PIC_INSTALL6,      "/pic/%d_%d/installing_6"},
    {LCD_PIC_INSTALL7,      "/pic/%d_%d/installing_7"},
    {LCD_PIC_INSTALL8,      "/pic/%d_%d/installing_8"},
    {LCD_PIC_INSTALL9,      "/pic/%d_%d/installing_9"},
    {LCD_PIC_INSTALL10,     "/pic/%d_%d/installing_10"},
    {LCD_PIC_INSTALL11,     "/pic/%d_%d/installing_11"},
};

/* LCD 运行状态列表 */
STATIC upstate_info_t upstateinfo_st[] =
{
    /* LCD显示配置 */
    /* 空闲状态显示序列 */
    {DLOAD_STATE_NORMAL_IDLE,      LCD_READ,   {.path_index = LCD_PIC_INSTALL0},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,      LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},

    /* 通用运行状态显示序列 */
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL0},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL1},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL2},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL3},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL4},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL5},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL6},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL7},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL8},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL9},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL10},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL11},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},

    /* 在线升级运行状态显示序列 */
    {DLOAD_STATE_AUTOUG_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_AUTOUG},       SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},

    /* 低电状态显示序列 */
    {DLOAD_STATE_NORMAL_LOW_POWER, LCD_READ,   {.path_index = LCD_PIC_LOWPOWER},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_LOW_POWER, LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},

    /* 升级成功状态显示序列 */
    {DLOAD_STATE_NORMAL_SUCCESS,   LCD_READ,   {.path_index = LCD_PIC_SUCCESS},      SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},

    /* 升级失败状态显示序列 */
    {DLOAD_STATE_NORMAL_FAIL,      LCD_READ,   {.path_index = LCD_PIC_FAILED},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,      LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},

};
#else
STATIC path_info_t pathinfo_st[] =
{
    {LED_LTE_GREEN_ATTR_ONOFF,       "/sys/class/leds/lte_led:green/trigger"},
    {LED_LTE_GREEN_ATTR_DELAY_ON,    "/sys/class/leds/lte_led:green/delay_on"},
    {LED_LTE_GREEN_ATTR_DELAY_OFF,   "/sys/class/leds/lte_led:green/delay_off"},
    {LED_BAT_GREEN_ATTR_ONOFF,       "/sys/class/leds/bat_led:green/trigger"},
    {LED_BAT_GREEN_ATTR_DELAY_ON,    "/sys/class/leds/bat_led:green/delay_on"},
    {LED_BAT_GREEN_ATTR_DELAY_OFF,   "/sys/class/leds/bat_led:green/delay_off"},

};
STATIC upstate_info_t upstateinfo_st[] =
{
    /* 空闲状态显示序列 */
    {DLOAD_STATE_NORMAL_IDLE,   LED_READ,   {.str_value  = "timer"},                     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_ONOFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_OFF},SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_ON}, SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_READ,   {.str_value  = "timer"},                     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_WRITE,  {.path_index = LED_BAT_GREEN_ATTR_ONOFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_WRITE,  {.path_index = LED_BAT_GREEN_ATTR_DELAY_OFF},SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,   LED_WRITE,  {.path_index = LED_BAT_GREEN_ATTR_DELAY_ON}, SHOW_NOT_DELAY},

    /* 通用运行状态显示序列 */
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "timer"},                     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_ONOFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_OFF},SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_ON}, SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "timer"},                     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_BAT_GREEN_ATTR_ONOFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_BAT_GREEN_ATTR_DELAY_OFF},SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_BAT_GREEN_ATTR_DELAY_ON}, SHOW_NOT_DELAY},

    /* 升级成功状态显示序列 */
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "timer"},                     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_ONOFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_OFF},SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_ON}, SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "timer"},                     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_BAT_GREEN_ATTR_ONOFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_BAT_GREEN_ATTR_DELAY_OFF},SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_BAT_GREEN_ATTR_DELAY_ON}, SHOW_NOT_DELAY},

    /* 升级失败状态显示序列 */
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "timer"},                     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_ONOFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_OFF},SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_LTE_GREEN_ATTR_DELAY_ON}, SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "timer"},                     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_BAT_GREEN_ATTR_ONOFF},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_BAT_GREEN_ATTR_DELAY_OFF},SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_READ,   {.str_value  = "500"},                       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,   LED_WRITE,  {.path_index = LED_BAT_GREEN_ATTR_DELAY_ON}, SHOW_NOT_DELAY},


};
#endif
#endif/*MBB_LED_LCD_UNIFORM*/
#else
#define SHOW_YES_DELAY         (1000000) /*延时1s*/

STATIC path_info_t pathinfo_st[] =
{
    {LCD_DEV_NAME,          "/dev/fb0"},
    {LCD_PIC_SUCCESS,       "/pic/%d_%d/upgrade_success"},
    {LCD_PIC_FAILED,        "/pic/%d_%d/upgrade_fail"},
    {LCD_PIC_AUTOUG,        "/pic/%d_%d/auto_update"},
    {LCD_PIC_LOWPOWER,      "/pic/%d_%d/lowpower"},
    {LCD_PIC_INSTALL0,      "/pic/%d_%d/installing_0"},
    {LCD_PIC_INSTALL1,      "/pic/%d_%d/installing_1"},
    {LCD_PIC_INSTALL2,      "/pic/%d_%d/installing_2"},
    {LCD_PIC_INSTALL3,      "/pic/%d_%d/installing_3"},
    {LCD_PIC_INSTALL4,      "/pic/%d_%d/installing_4"},
    {LCD_PIC_INSTALL5,      "/pic/%d_%d/installing_5"},
    {LCD_PIC_INSTALL6,      "/pic/%d_%d/installing_6"},
    {LCD_PIC_INSTALL7,      "/pic/%d_%d/installing_7"},
    {LCD_PIC_INSTALL8,      "/pic/%d_%d/installing_8"},
    {LCD_PIC_INSTALL9,      "/pic/%d_%d/installing_9"},
    {LCD_PIC_INSTALL10,     "/pic/%d_%d/installing_10"},
    {LCD_PIC_INSTALL11,     "/pic/%d_%d/installing_11"},
    {LED_ATTR_ONOFF,        "/sys/class/leds/test-backlight/trigger"},
    {LED_ATTR_BRIGHT,       "/sys/class/leds/test-backlight/brightness"},
    {LED_ATTR_DELAY_ON,     "/sys/class/leds/test-backlight/delay_on"},
    {LED_ATTR_DELAY_OFF,    "/sys/class/leds/test-backlight/delay_off"},
};

/* LCD 运行状态列表 */
STATIC upstate_info_t upstateinfo_st[] =
{
    /* LCD显示配置 */
    /* 空闲状态显示序列 */
    {DLOAD_STATE_NORMAL_IDLE,      LCD_READ,   {.path_index = LCD_PIC_INSTALL0},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,      LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},

    /* 通用运行状态显示序列 */
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL0},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL1},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL2},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL3},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL4},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL5},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL6},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL7},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL8},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL9},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL10},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_INSTALL11},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},

    /* 在线升级运行状态显示序列 */
    {DLOAD_STATE_AUTOUG_RUNNING,   LCD_READ,   {.path_index = LCD_PIC_AUTOUG},       SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},

    /* 低电状态显示序列 */
    {DLOAD_STATE_NORMAL_LOW_POWER, LCD_READ,   {.path_index = LCD_PIC_LOWPOWER},     SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_LOW_POWER, LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},

    /* 升级成功状态显示序列 */
    {DLOAD_STATE_NORMAL_SUCCESS,   LCD_READ,   {.path_index = LCD_PIC_SUCCESS},      SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},

    /* 升级失败状态显示序列 */
    {DLOAD_STATE_NORMAL_FAIL,      LCD_READ,   {.path_index = LCD_PIC_FAILED},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,      LCD_WRITE,  {.path_index = LCD_DEV_NAME},         SHOW_YES_DELAY},

    /* LED显示配置 */
    /* 空闲状态显示序列 */
    {DLOAD_STATE_NORMAL_IDLE,      LED_READ,   {.str_value  = "1"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,      LED_WRITE,  {.path_index = LED_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,      LED_READ,   {.str_value  = "3000"},               SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,      LED_WRITE,  {.path_index = LED_ATTR_BRIGHT},      SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,      LED_READ,   {.str_value  = "50"},                 SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,      LED_WRITE,  {.path_index = LED_ATTR_DELAY_ON},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,      LED_READ,   {.str_value  = "50"},                 SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_IDLE,      LED_WRITE,  {.path_index = LED_ATTR_DELAY_OFF},   SHOW_NOT_DELAY},

    {DLOAD_STATE_FAIL,      LED_READ,   {.str_value  = "1"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_FAIL,      LED_WRITE,  {.path_index = LED_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_FAIL,      LED_READ,   {.str_value  = "3000"},               SHOW_NOT_DELAY},
    {DLOAD_STATE_FAIL,      LED_WRITE,  {.path_index = LED_ATTR_BRIGHT},      SHOW_NOT_DELAY},
    {DLOAD_STATE_FAIL,      LED_READ,   {.str_value  = "50"},                 SHOW_NOT_DELAY},
    {DLOAD_STATE_FAIL,      LED_WRITE,  {.path_index = LED_ATTR_DELAY_ON},    SHOW_NOT_DELAY},
    {DLOAD_STATE_FAIL,      LED_READ,   {.str_value  = "50"},                 SHOW_NOT_DELAY},
    {DLOAD_STATE_FAIL,      LED_WRITE,  {.path_index = LED_ATTR_DELAY_OFF},   SHOW_NOT_DELAY},

    /* 通用运行状态显示序列 */
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "1"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "3000"},               SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_ATTR_BRIGHT},      SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "50"},                 SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_ATTR_DELAY_ON},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_READ,   {.str_value  = "50"},                 SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_RUNNING,   LED_WRITE,  {.path_index = LED_ATTR_DELAY_OFF},   SHOW_NOT_DELAY},

    /* 在线升级状态显示序列 */
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_READ,   {.str_value  = "1"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_WRITE,  {.path_index = LED_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_READ,   {.str_value  = "3000"},               SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_WRITE,  {.path_index = LED_ATTR_BRIGHT},      SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_READ,   {.str_value  = "50"},                 SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_WRITE,  {.path_index = LED_ATTR_DELAY_ON},    SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_READ,   {.str_value  = "50"},                 SHOW_NOT_DELAY},
    {DLOAD_STATE_AUTOUG_RUNNING,   LED_WRITE,  {.path_index = LED_ATTR_DELAY_OFF},   SHOW_NOT_DELAY},

    /* 低电状态显示序列 */
    {DLOAD_STATE_NORMAL_LOW_POWER, LED_READ,   {.str_value  = "1"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_LOW_POWER, LED_WRITE,  {.path_index = LED_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_LOW_POWER, LED_READ,   {.str_value  = "3000"},               SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_LOW_POWER, LED_WRITE,  {.path_index = LED_ATTR_BRIGHT},      SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_LOW_POWER, LED_READ,   {.str_value  = "50"},                 SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_LOW_POWER, LED_WRITE,  {.path_index = LED_ATTR_DELAY_ON},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_LOW_POWER, LED_READ,   {.str_value  = "50"},                 SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_LOW_POWER, LED_WRITE,  {.path_index = LED_ATTR_DELAY_OFF},   SHOW_NOT_DELAY},

    /* 升级成功状态显示序列 */
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "1"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "3000"},               SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_ATTR_BRIGHT},      SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "50"},                 SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_ATTR_DELAY_ON},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_READ,   {.str_value  = "50"},                 SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_SUCCESS,   LED_WRITE,  {.path_index = LED_ATTR_DELAY_OFF},   SHOW_NOT_DELAY},

    /* 升级失败状态显示序列 */
    {DLOAD_STATE_NORMAL_FAIL,      LED_READ,   {.str_value  = "1"},                  SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,      LED_WRITE,  {.path_index = LED_ATTR_ONOFF},       SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,      LED_READ,   {.str_value  = "3000"},               SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,      LED_WRITE,  {.path_index = LED_ATTR_BRIGHT},      SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,      LED_READ,   {.str_value  = "50"},                 SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,      LED_WRITE,  {.path_index = LED_ATTR_DELAY_ON},    SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,      LED_READ,   {.str_value  = "50"},                 SHOW_NOT_DELAY},
    {DLOAD_STATE_NORMAL_FAIL,      LED_WRITE,  {.path_index = LED_ATTR_DELAY_OFF},   SHOW_NOT_DELAY},

};
#endif

#if (FEATURE_ON == MBB_LED_LCD_UNIFORM)
/*用来保存升级需要的路径信息及其路径信息个数
和升级状态信息及其升级状态个数*/
path_info_t *pathinfo_st = NULL;
upstate_info_t  *upstateinfo_st = NULL;
uint32 pathinfo_num = 0;
uint32 upstateinfo_num = 0;

/*采用LCD与LED归一化方案，新增产品需要配置此表格*/
/*配置信息为硬件ID,path info,upstate info,led support,lcd support,pathinfo 
个数，upstate 个数*/
product_dload_adapt_t dload_uniform_info[] = {
{HW_VER_PRODUCT_E5785Lh_92a,pathinfo_st_E5785Lh_92a,upstateinfo_st_E5785Lh_92a,FALSE,TRUE,\
    (sizeof(pathinfo_st_E5785Lh_92a) / sizeof(path_info_t)),(sizeof(upstateinfo_st_E5785Lh_92a) / sizeof(upstate_info_t))},
{HW_VER_PRODUCT_E5785Lh_23c,pathinfo_st_E5785Lh_92a,upstateinfo_st_E5785Lh_92a,FALSE,TRUE,\
    (sizeof(pathinfo_st_E5785Lh_92a) / sizeof(path_info_t)),(sizeof(upstateinfo_st_E5785Lh_92a) / sizeof(upstate_info_t))},
{HW_VER_PRODUCT_E5783h_92a,pathinfo_st_E5873h_92a,upstateinfo_st_E5783h_92a,TRUE,FALSE,\
    (sizeof(pathinfo_st_E5873h_92a) / sizeof(path_info_t)),(sizeof(upstateinfo_st_E5783h_92a) / sizeof(upstate_info_t))},
};

/*******************************************************************
  函数名称  : dload_uniform_init
  函数描述  : 完成函数dload 初始化需要的参数,支持lcd or led,升级需要
  的路径信息和参数。
  函数入参  : 硬件ID
  函数输出  : 对LCD 与LED特性的支持情况
  函数返回值: DLOAD_ERR 表示失败，DLOAD_OK 表示成功
********************************************************************/

int32  dload_uniform_init(uint32 product_id, bool *lcd_feature_support, bool *led_feature_support)
{
    uint32 i = 0;
    
    if(NULL == lcd_feature_support || NULL == led_feature_support)
    {

        DLOAD_PRINT(KERN_ERR, "lcd_feature_support or led_feature_support is NULL\n");
        return DLOAD_ERR;

    }
    for (i = 0; i < sizeof(dload_uniform_info) / sizeof(product_dload_adapt_t);i++)
    {
        /*根据硬件ID 匹配对应产品升级 所需要的路径信息*/
        if(product_id == dload_uniform_info[i].product_id)
        {
            *lcd_feature_support = dload_uniform_info[i].lcd_feature;
            *led_feature_support = dload_uniform_info[i].led_feature;
            pathinfo_st = dload_uniform_info[i].pPathinfo;
            upstateinfo_st = dload_uniform_info[i].pUpstate;            
            pathinfo_num = dload_uniform_info[i].pathinfo_num;
            upstateinfo_num = dload_uniform_info[i].upstate_num;
            break;            
        }
    }
    /*如果没有找到，则报错，说明配置有问题，需要排查软硬件适配*/
    if(i == ((sizeof(dload_uniform_info))/ (sizeof(product_dload_adapt_t))))
    {
        DLOAD_PRINT(KERN_ERR,"not match please check");
        return DLOAD_ERR;
    }
    else
    {
        return DLOAD_OK;
    }
}
#endif/*MBB_LED_LCD_UNIFORM*/
/*******************************************************************
  函数名称  : get_product_mark
  函数描述  : 获取产品硬件标识码
  函数入参  : NA
  函数输出  : NA
  函数返回值: 硬件标识
********************************************************************/
static uint32  get_product_mark(void)
{
    uint32 hw_main = bsp_get_version_info()->board_id;

    g_product_id = (hw_main >> PRODUCT_OFFSET) & 0xFF;
    g_big_ver = hw_main & 0xFF;

    return 0;

}

/*******************************************************************
  函数名称  : get_product_info
  函数描述  : 获取产品配置信息
  函数入参  : NA
  函数输出  : NA
  函数返回值: 产品信息结构
********************************************************************/
product_info_t*  get_product_info(void)
{
    uint32  ret = 0;
    uint32  index = 0;
    uint32  count = 0;
    product_info_t*  local_product_info_st = NULL;

    /* 产品标识获取 */
    ret = get_product_mark();
    if(0 != ret)
    {
        return NULL;
    }

    count = sizeof(product_info_st) / sizeof(product_info_t);

    for(index = 0; index < count; index ++)
    {
        local_product_info_st = &product_info_st[index];
        if((g_product_id == (uint8)local_product_info_st->hw_major_id) &&
            (g_big_ver == (uint16)local_product_info_st->hw_minor_id))
        {
            return local_product_info_st;
        }
    }

    DLOAD_PRINT(KERN_ERR, "g_product_id = %u  g_big_ver = %u  product_info is NULL.", g_product_id, g_big_ver);

    return NULL;
}

/*******************************************************************
  函数名称  : get_dload_feature
  函数描述  : 获取升级特性配置信息
  函数入参  : NA
  函数输出  : NA
  函数返回值: 产品信息结构
********************************************************************/
dload_feature_t*  get_dload_feature(void)
{
    uint32  index = 0;
    uint32  count = 0;
    dload_feature_t*  local_dload_feature_st = NULL;
    dload_smem_info_t* smem_info = NULL;
    count = sizeof(dload_feature_st) / sizeof(dload_feature_t);

    smem_info = get_smem_info();

    for(index = 0; index < count; index ++)
    {
        local_dload_feature_st = &dload_feature_st[index];
        if((g_product_id == (uint8)local_dload_feature_st->hw_major_id) &&
            (g_big_ver == (uint16)local_dload_feature_st->hw_minor_id))
        {
#if  (FEATURE_ON == MBB_DLOAD_VER_VERIFY)
            local_dload_feature_st->safety1_3_dload.safe_support = TRUE;
#else
            local_dload_feature_st->safety1_3_dload.safe_support = FALSE;
#endif
            if(SMEM_BURN_UPDATE_FLAG_NUM == *((uint32*)(smem_info->ut_dload_addr)))
            {
                /* 为烧片版本，置烧片版本标识，不启动安全校验 */
                /* 数据卡烧片版本和正常版本led显示不一致 */
#if (FEATURE_ON == MBB_DLOAD_STICK || FEATURE_ON == MBB_DLOAD_HILINK || FEATURE_ON == MBB_DLOAD_WINGLE)
                dload_burn = TRUE;
#endif
                if(SMEM_DT_UPDATE_FLAG_NUM == *((uint32*)(smem_info->dt_dload_addr)))
                {
                    local_dload_feature_st->safety_dload = FALSE;
                    local_dload_feature_st->safety1_3_dload.safe_support = FALSE;
                }
            }
            return local_dload_feature_st;
        }
    }

    return NULL;
}

/*******************************************************************
  函数名称  : get_show_info
  函数描述  : 获取path 和path_index转换的数组
  函数入参  : NA
  函数输出  : pppath_info_st : pathinfo_st 数组的地址
                            info_size: pathinfo_st的size
  函数返回值: DLOAD_OK    : 成功
              DLOAD_ERR   : 失败
********************************************************************/
uint32  get_show_path_info(path_info_t **pppath_info_st, uint32 *info_size)
{
    if(NULL != pppath_info_st)
    {
        if(FALSE == dload_burn)
        {
            *pppath_info_st = pathinfo_st;
        }
#if (FEATURE_ON == MBB_DLOAD_STICK || FEATURE_ON == MBB_DLOAD_HILINK || FEATURE_ON == MBB_DLOAD_WINGLE)
        else
        {
            *pppath_info_st = pathinfo_burn_st;
        }
#endif
    }
    if(NULL != info_size)
    {
        if(FALSE == dload_burn)
        {
/*led与lcd归一化配置，升级路径个数适配*/
#if (FEATURE_ON == MBB_LED_LCD_UNIFORM)
            *info_size = pathinfo_num;
#else
            *info_size = sizeof(pathinfo_st) / sizeof(path_info_t);
#endif
        }
#if (FEATURE_ON == MBB_DLOAD_STICK || FEATURE_ON == MBB_DLOAD_HILINK || FEATURE_ON == MBB_DLOAD_WINGLE)
        else
        {
            *info_size = sizeof(pathinfo_burn_st) / sizeof(path_info_t);
        }
#endif
    }
    return DLOAD_OK;

}

/*******************************************************************
  函数名称  : get_show_info
  函数描述  : 获取lcd/led配置信息
  函数入参  : NA
  函数输出  : ppupstate_info : upstateinfo_st 数组的地址
                            data_len: upstate_info_st的size
  函数返回值: DLOAD_OK    : 成功
              DLOAD_ERR   : 失败
********************************************************************/
uint32  get_show_info(upstate_info_t **ppupstate_info, uint32 *info_size)
{
    if(NULL != ppupstate_info)
    {
        if(FALSE == dload_burn)
        {
            *ppupstate_info = upstateinfo_st;
        }
#if (FEATURE_ON == MBB_DLOAD_STICK || FEATURE_ON == MBB_DLOAD_HILINK || FEATURE_ON == MBB_DLOAD_WINGLE)
        else
        {
            *ppupstate_info = upstateinfo_burn_st;
        }
#endif
    }
    if(NULL != info_size)
    {
        if(FALSE == dload_burn)
        {
/*led与lcd归一化配置，升级状态个数适配*/
#if (FEATURE_ON == MBB_LED_LCD_UNIFORM)
            *info_size = upstateinfo_num;  
#else
            *info_size = sizeof(upstateinfo_st) / sizeof(upstate_info_t);
#endif
        }
#if (FEATURE_ON == MBB_DLOAD_STICK || FEATURE_ON == MBB_DLOAD_HILINK || FEATURE_ON == MBB_DLOAD_WINGLE)
        else
        {
            *info_size= sizeof(upstateinfo_burn_st) / sizeof(upstate_info_t);
        }
#endif
    }
    return DLOAD_OK;

}



#ifdef  __cplusplus
    }
#endif
