/*
 * Copyright (C) Huawei Technologies Co., Ltd. 2013-2015. All rights reserved.
 *
 * mobile@huawei.com
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 */
/* This file should be auto-generated by tool, please don't manully modify it.*/

#include "../hisi_battery_data.h"

static struct single_row_lut xinwangda_1500_fcc_temp = {
    .x        = {-20, -10, 0, 25, 40, 60},
    .y        = {1461, 1460, 1474, 1486, 1485, 1475},
    .cols    = 6
};

static struct single_row_lut xinwangda_1500_fcc_sf = {
    .x        = {0, 100, 200, 300, 400, 500},
    .y        = {100, 96, 94, 92, 90, 88},
    .cols    = 6
};

static struct sf_lut xinwangda_1500_pc_sf = {
    .rows        = 1,
    .cols        = 1,
    .row_entries        = {0},
    .percent    = {100},
    .sf            = {
                {100}
    }
};

static struct sf_lut xinwangda_1500_rbatt_sf = {
        .rows           = 28,
        .cols           = 6,
        /* row_entries are temperature */
        .row_entries            = {-20, -10, 0, 25, 40, 60},
        .percent        = {100, 95, 90, 85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1},
        .sf                     = {
                    {1894,   711,     310 ,     100,    68 ,   65},
                    {1816,   711,     316 ,     103,    69 ,   65},
                    {1828,   746,     332 ,     107,    72 ,   66},
                    {1765,   748,     343 ,     113,    75 ,   68},
                    {1715,   742,     352 ,     120,    78 ,   70},
                    {1679,   726,     356 ,     131,    83 ,   72},
                    {1665,   723,     342 ,     140,    90 ,   76},
                    {1656,   720,     330 ,     141,    98 ,   81},
                    {1662,   724,     320 ,     116,    81 ,   72},
                    {1688,   731,     320 ,     107,    72 ,   67},
                    {1728,   744,     323 ,     107,    72 ,   66},
                    {1784,   776,     331 ,     110,    74 ,   67},
                    {1846,   815,     342 ,     115,    77 ,   69},
                    {1924,   858,     360 ,     119,    81 ,   71},
                    {2025,   914,     377 ,     117,    76 ,   67},
                    {2161,   987,     398 ,     110,    74 ,   66},
                    {2346,   1085,    414 ,     109,    73 ,   67},
                    {2596,   1239,    450 ,     112,    73 ,   66},
                    {3001,   1606,    550 ,     121,    76 ,   68},
                    {3100,   1707,    574 ,     123,    77 ,   69},
                    {3304,   1811,    551 ,     121,    77 ,   70},
                    {4243,   1905,    532 ,     118,    77 ,   68},
                    {4904,   2027,    542 ,     117,    76 ,   67},
                    {5498,   2316,    594 ,     118,    76 ,   69},
                    {6293,   2716,    658 ,     124,    78 ,   70},
                    {7308,   3261,    743 ,     130,    82 ,   71},
                    {8653,   4263,    953,      137,    87 ,   73},
                    {10422,  6073,    1447,     168,    111,   80}
                    }
};

static struct pc_temp_ocv_lut xinwangda_1500_pc_temp_ocv = {
    .rows        = 29,
    .cols        = 6,
    .temp        = {-20, -10, 0, 25, 40, 60},
    .percent    = {100, 95, 90, 85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0},
    .ocv        = {
                    {4292,  4282,  4283,  4277,  4273,  4266}, 
                    {4198,  4206,  4214,  4217,  4214,  4208}, 
                    {4131,  4148,  4159,  4163,  4161,  4156}, 
                    {4067,  4093,  4108,  4113,  4111,  4106}, 
                    {4006,  4040,  4058,  4066,  4064,  4060}, 
                    {3955,  3987,  4011,  4022,  4020,  4016}, 
                    {3910,  3943,  3963,  3980,  3980,  3977}, 
                    {3871,  3903,  3921,  3938,  3940,  3938}, 
                    {3837,  3869,  3883,  3894,  3895,  3895}, 
                    {3810,  3838,  3852,  3859,  3861,  3860}, 
                    {3787,  3812,  3826,  3834,  3835,  3834}, 
                    {3768,  3792,  3804,  3813,  3814,  3813}, 
                    {3749,  3778,  3787,  3796,  3798,  3796}, 
                    {3729,  3763,  3774,  3781,  3783,  3781}, 
                    {3710,  3750,  3763,  3765,  3761,  3753}, 
                    {3692,  3735,  3750,  3746,  3739,  3728}, 
                    {3675,  3713,  3728,  3726,  3720,  3708}, 
                    {3656,  3680,  3697,  3698,  3694,  3682}, 
                    {3628,  3642,  3660,  3671,  3671,  3660}, 
                    {3621,  3634,  3653,  3666,  3666,  3656}, 
                    {3614,  3627,  3647,  3663,  3662,  3651}, 
                    {3606,  3620,  3642,  3655,  3654,  3644}, 
                    {3596,  3611,  3630,  3639,  3637,  3626}, 
                    {3581,  3596,  3610,  3609,  3605,  3594}, 
                    {3562,  3572,  3575,  3566,  3561,  3553}, 
                    {3538,  3532,  3522,  3512,  3508,  3501}, 
                    {3506,  3476,  3452,  3441,  3439,  3435}, 
                    {3463,  3402,  3356,  3343,  3345,  3344}, 
                    {3200,  3200,  3200,  3200,  3200,  3200}
            }
};

static struct hisi_smartstar_coul_battery_data xinwangda_1500_battery_data = {
        .id_voltage_min = 1350,
        .id_voltage_max = 1600,
        .fcc            = 1486,
        .fcc_temp_lut        = &xinwangda_1500_fcc_temp,
        .fcc_sf_lut        = &xinwangda_1500_fcc_sf,
        .pc_temp_ocv_lut    = &xinwangda_1500_pc_temp_ocv,
        .pc_sf_lut        = &xinwangda_1500_pc_sf,
        .rbatt_sf_lut        = &xinwangda_1500_rbatt_sf,
        .default_rbatt_mohm        = 199,
        .max_currentmA = 1000,
        .max_voltagemV = 4300,
        .max_cin_currentmA = 1200,
};

